# Use a full Debian-based Python image (not slim) for compiling dlib
FROM python:3.8.10-slim

# Install OS dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libopenblas-dev \
    liblapack-dev \
    libx11-dev \
    libgtk-3-dev \
    libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy all files
COPY . .

# Install Python packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose the port Flask will run on
EXPOSE 8000

# Start the app with gunicorn
CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:8000", "faceRecognition:app"]
